import { LanguageOption, Plan } from './types';

export const supportedLanguages: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇬🇧', popular: true },
  { code: 'pt', label: 'Portuguese', nativeLabel: 'Português', flag: '🇵🇹', popular: true },
  { code: 'es', label: 'Spanish', nativeLabel: 'Spanish', flag: '🇪🇸', popular: true },
  { code: 'fr', label: 'French', nativeLabel: 'French', flag: '🇫🇷', popular: true },
  { code: 'de', label: 'German', nativeLabel: 'Deutsch', flag: '🇩🇪', popular: true },
  { code: 'it', label: 'Italian', nativeLabel: 'Italiano', flag: '🇮🇹', popular: true },
  { code: 'zh', label: 'Chinese', nativeLabel: '中文', flag: '🇨🇳', popular: true },
  { code: 'ja', label: 'Japanese', nativeLabel: '日本語', flag: '🇯🇵', popular: true },
  { code: 'ko', label: 'Korean', nativeLabel: '한국어', flag: '🇰🇷' },
  { code: 'ar', label: 'Arabic', nativeLabel: 'العربية', flag: '🇸🇦' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ru', label: 'Russian', nativeLabel: 'Русский', flag: '🇷🇺' },
  { code: 'nl', label: 'Dutch', nativeLabel: 'Nederlands', flag: '🇳🇱' },
  { code: 'tr', label: 'Turkish', nativeLabel: 'Türkçe', flag: '🇹🇷' },
  { code: 'pl', label: 'Polish', nativeLabel: 'Polski', flag: '🇵🇱' },
  { code: 'uk', label: 'Ukrainian', nativeLabel: 'Українська', flag: '🇺🇦' },
  { code: 'vi', label: 'Vietnamese', nativeLabel: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'id', label: 'Indonesian', nativeLabel: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'th', label: 'Thai', nativeLabel: 'ไทย', flag: '🇹🇭' },
  { code: 'sv', label: 'Swedish', nativeLabel: 'Svenska', flag: '🇸🇪' },
  { code: 'no', label: 'Norwegian', nativeLabel: 'Norsk', flag: '🇳🇴' },
  { code: 'da', label: 'Danish', nativeLabel: 'Dansk', flag: '🇩🇰' },
  { code: 'fi', label: 'Finnish', nativeLabel: 'Suomi', flag: '🇫🇮' },
  { code: 'cs', label: 'Czech', nativeLabel: 'Čeština', flag: '🇨🇿' },
  { code: 'el', label: 'Greek', nativeLabel: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'he', label: 'Hebrew', nativeLabel: 'עברית', flag: '🇮🇱' },
  { code: 'ro', label: 'Romanian', nativeLabel: 'Română', flag: '🇷🇴' },
  { code: 'hu', label: 'Hungarian', nativeLabel: 'Magyar', flag: '🇭🇺' },
  { code: 'sw', label: 'Swahili', nativeLabel: 'Kiswahili', flag: '🇰🇪' },
  { code: 'fa', label: 'Persian', nativeLabel: 'فارسی', flag: '🇮🇷' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇧🇩' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  { code: 'ms', label: 'Malay', nativeLabel: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'fil', label: 'Filipino', nativeLabel: 'Filipino', flag: '🇵🇭' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو', flag: '🇵🇰' },
  { code: 'am', label: 'Amharic', nativeLabel: 'አማርኛ', flag: '🇪🇹' },
];

export const plans: Plan[] = [
  { id: 'free', name: 'FREE', price: 0, currency: '$', billingCycle: 'month', translationMinutes: 10, connectMinutes: 0, features: ['10 Translation Minutes', 'English', 'French', 'Voice Translation', 'Text Translation'], tier: 'Essential' },
  { id: 'starter', name: 'STARTER', price: 9.99, currency: '$', billingCycle: 'month', translationMinutes: 30, connectMinutes: 10, features: ['30 Translation Minutes', '10 Connect Minutes', 'All supported languages', 'Translation history'], tier: 'Core' },
  { id: 'plus', name: 'PLUS', price: 19.99, currency: '$', billingCycle: 'month', translationMinutes: 75, connectMinutes: 25, features: ['75 Translation Minutes', '25 Connect Minutes', 'Priority processing', 'Full history'], popular: true, tier: 'Popular' },
  { id: 'pro', name: 'PRO', price: 34.99, currency: '$', billingCycle: 'month', translationMinutes: 150, connectMinutes: 50, features: ['150 Translation Minutes', '50 Connect Minutes', 'Advanced voice', 'Export'], tier: 'Pro' },
  { id: 'ultra', name: 'ULTRA', price: 59.99, currency: '$', billingCycle: 'month', translationMinutes: 300, connectMinutes: 100, features: ['300 Translation Minutes', '100 Connect Minutes', 'Highest priority', 'All premium features'], tier: 'Ultra' },
];
