export const localization = {
  appName: 'MUWOYO TRANSLATE',
  splashTagline: 'Translate without limits.',
  onboarding: {
    oneTitle: 'Speak. Translate. Understand.',
    oneDescription: 'Break language barriers with fast and natural translation.',
    twoTitle: 'Have conversations in any language.',
    twoDescription: 'Connect two people and translate the conversation in real time.',
    threeTitle: 'Your voice. Their language.',
    threeDescription: 'Speak naturally and let Muwoyo Translate handle the language barrier.',
  },
  translate: {
    greeting: 'Good afternoon',
    minuteBalance: '24 Translation min',
    tapToSpeak: 'Tap to speak',
    listening: 'Listening...',
    processing: 'Translating...',
    typeInstead: 'Type instead',
    copy: 'Copy',
    share: 'Share',
    play: 'Play',
    autoDetect: 'Auto Detect',
    languageSelectorTitle: 'Choose a language',
    search: 'Search languages',
  },
  connect: {
    title: 'Connect',
    subtitle: 'Talk naturally across languages.',
    start: 'Start Connect',
    remaining: '18:42 Connect remaining',
  },
  profile: {
    account: 'Account',
    subscription: 'Subscription',
    usage: 'Usage',
    languages: 'Languages',
    voice: 'Voice',
    notifications: 'Notifications',
    appearance: 'Appearance',
    privacy: 'Privacy',
    help: 'Help',
    about: 'About',
    signOut: 'Sign Out',
  },
  common: {
    continue: 'Continue',
    getStarted: 'Get Started',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    save: 'Save',
    next: 'Next',
    cancel: 'Cancel',
    confirm: 'Confirm',
    done: 'Done',
    viewPlans: 'View Plans',
  },
  subscription: {
    monthly: '/month',
    mostPopular: 'MOST POPULAR',
    currentPlan: 'Current Plan',
  },
};
